// Package internetgateways provides the gophercloud bindings for the NHN Cloud
// InternetGateway resource.
//
// Generated by tfcodegen (tc-iaas-compute/3327) from:
//
//	Network > Internet Gateway > API v2 가이드
//
// Do not edit generated boilerplate by hand; re-run the generator instead.
// Manual overrides belong in *_override.go files within this package.
package internetgateways
